import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Check, ChevronDown, Menu, X, Mail, Linkedin, Download, MoveUpRight } from 'lucide-react';

const cases = [
  { id: '01', tag: 'B2B SaaS · Activation', title: 'Finding the moment users become believers.', result: '+31%', resultLabel: 'activation rate', accent: 'lime', description: 'Reframed an onboarding funnel around the first meaningful action, not the first login.', details: ['Mapped 14,000+ user journeys to identify the first value event.', 'Shipped a behavioral onboarding experiment across three segments.', 'Built a weekly activation scorecard adopted by Product and Growth.'] },
  { id: '02', tag: 'Consumer · Retention', title: 'Making the second session feel inevitable.', result: '−18%', resultLabel: 'week-one churn', accent: 'peach', description: 'Connected product usage patterns to a retention model that gave the team a clearer north star.', details: ['Synthesized qualitative interviews with cohort-level product data.', 'Prioritized a re-engagement loop worth 2.4× more than paid retargeting.', 'Turned a monthly report into an always-on retention dashboard.'] },
  { id: '03', tag: 'Marketplace · Monetization', title: 'Less discounting. More conviction.', result: '+22%', resultLabel: 'net revenue / user', accent: 'blue', description: 'Rebuilt pricing insight from the ground up, uncovering where willingness to pay was hiding.', details: ['Designed a willingness-to-pay survey across high-intent cohorts.', 'Identified a high-value segment underserved by current packaging.', 'Partnered with Marketing on a new value-led pricing narrative.'] },
];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeCase, setActiveCase] = useState('01');
  const [openFaq, setOpenFaq] = useState(0);
  const [sent, setSent] = useState(false);
  const active = cases.find(c => c.id === activeCase);

  const navigate = (id) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  const submit = (e) => { e.preventDefault(); setSent(true); };

  return <div className="app-shell min-h-screen text-cream">
    <div className="noise" aria-hidden="true" />
    <header className="relative z-30 border-b rule">
      <div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 md:px-8">
        <button onClick={() => navigate('top')} className="display text-xl font-bold tracking-[-.05em]" aria-label="Go to top">rahul<span className="text-lime">.</span></button>
        <nav className="hidden items-center gap-9 text-[11px] font-semibold uppercase tracking-[.16em] text-cream/60 md:flex" aria-label="Main navigation">
          <button className="nav-link hover:text-cream" onClick={() => navigate('work')}>Selected work</button>
          <button className="nav-link hover:text-cream" onClick={() => navigate('approach')}>Approach</button>
          <button className="nav-link hover:text-cream" onClick={() => navigate('contact')}>Contact</button>
        </nav>
        <a href="mailto:hello@rahul.work" className="hidden items-center gap-2 rounded-full border border-lime/50 px-4 py-2 text-[11px] font-bold uppercase tracking-[.13em] text-lime transition hover:bg-lime hover:text-ink sm:flex">Let's talk <ArrowUpRight size={13} /></a>
        <button className="text-cream md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <div className="border-t rule bg-ink px-5 py-5 md:hidden"><div className="flex flex-col gap-5 text-sm text-cream/70"><button onClick={() => navigate('work')} className="text-left">Selected work</button><button onClick={() => navigate('approach')} className="text-left">Approach</button><button onClick={() => navigate('contact')} className="text-left">Contact</button></div></div>}
    </header>

    <main id="top">
      <section className="relative isolate overflow-hidden border-b rule">
        <div className="grid-lines absolute inset-0 -z-10" /><div className="hero-orb absolute -right-32 top-8 -z-10 h-[500px] w-[500px] rounded-full" />
        <div className="mx-auto grid min-h-[650px] max-w-[1240px] items-center gap-14 px-5 py-20 md:px-8 lg:grid-cols-[1.08fr_.92fr] lg:gap-8 lg:py-24">
          <div className="reveal"><p className="mb-7 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.22em] text-lime"><span className="h-2 w-2 rounded-full bg-lime shadow-[0_0_15px_#c7f36b]" /> Growth analyst · Bengaluru / remote</p>
            <h1 className="display max-w-[760px] text-[clamp(3.7rem,8vw,7.7rem)] font-medium leading-[.89] tracking-[-.075em]">I turn <span className="text-lime">signals</span><br />into momentum.</h1>
            <p className="mt-9 max-w-[480px] text-base leading-7 text-cream/60 md:text-lg">I help ambitious teams find the insight between the data points — then turn it into growth people can feel.</p>
            <div className="mt-10 flex flex-wrap items-center gap-5"><button onClick={() => navigate('work')} className="group flex items-center gap-3 rounded-full bg-lime px-5 py-3 text-xs font-bold uppercase tracking-[.13em] text-ink transition hover:gap-5">Explore the work <ArrowDownRight size={15} /></button><button onClick={() => navigate('contact')} className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-cream/70 transition hover:text-lime">Start a conversation <ArrowUpRight size={14} /></button></div>
          </div>
          <div className="reveal delay-2 relative mx-auto w-full max-w-[410px] lg:ml-auto"><div className="glass relative aspect-[.85] overflow-hidden rounded-[2rem] p-6 shadow-[0_30px_100px_rgba(0,0,0,.28)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_22%,rgba(199,243,107,.25),transparent_24%),linear-gradient(145deg,rgba(255,255,255,.07),transparent_60%)]" /><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between text-[10px] uppercase tracking-[.2em] text-cream/45"><span>Signal / 001</span><span>2024—25</span></div><div><div className="mb-5 text-7xl font-medium tracking-[-.08em] text-lime md:text-8xl">+31<span className="text-3xl">%</span></div><p className="max-w-[180px] text-sm leading-5 text-cream/70">activation unlocked by asking a better question.</p></div><div className="flex items-end justify-between"><div className="flex items-end gap-1.5"><i className="h-8 w-2 rounded-t bg-cream/20" /><i className="h-12 w-2 rounded-t bg-cream/30" /><i className="h-16 w-2 rounded-t bg-cream/40" /><i className="h-24 w-2 rounded-t bg-lime" /><i className="h-32 w-2 rounded-t bg-lime" /><i className="h-40 w-2 rounded-t bg-lime/40" /></div><span className="text-[10px] uppercase tracking-[.16em] text-cream/45">value over vanity</span></div></div></div><div className="absolute -bottom-5 -left-5 flex h-[92px] w-[92px] rotate-[-12deg] items-center justify-center rounded-full border border-lime/40 bg-ink text-center text-[10px] font-bold uppercase leading-3 tracking-[.15em] text-lime">Curious<br />by default</div></div>
        </div>
      </section>

      <section className="mx-auto max-w-[1240px] px-5 py-16 md:px-8 md:py-20"><div className="grid gap-8 md:grid-cols-3"><div className="text-[11px] font-bold uppercase tracking-[.2em] text-cream/35">A little context</div><p className="max-w-[540px] text-xl leading-8 tracking-[-.025em] text-cream/85 md:col-span-2 md:text-2xl">Growth is rarely a single lever. It is the compounding effect of <span className="text-lime">clear questions, useful experiments,</span> and teams that know what to do next.</p></div></section>

      <section id="work" className="border-y rule bg-[#151812] px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-[1240px]"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 text-[11px] font-bold uppercase tracking-[.2em] text-lime">Selected work / 2023—25</p><h2 className="display text-4xl tracking-[-.055em] md:text-6xl">The useful kind<br />of <span className="text-cream/45">complicated.</span></h2></div><p className="max-w-[280px] text-sm leading-6 text-cream/50">A few moments where analysis moved from a spreadsheet into the real world.</p></div>
        <div className="grid gap-3 lg:grid-cols-[.75fr_1.25fr]"><div className="flex flex-col gap-2">{cases.map(c => <button key={c.id} onClick={() => setActiveCase(c.id)} className={`case-card flex items-start justify-between border p-5 text-left ${activeCase === c.id ? 'border-lime/50 bg-white/[.07]' : 'border-white/[.09]'}`}><div><div className="mb-4 text-[10px] font-bold tracking-[.18em] text-cream/35">{c.id} / {c.tag}</div><div className="max-w-[240px] text-lg leading-6 tracking-[-.03em]">{c.title}</div></div><ArrowUpRight size={17} className={activeCase === c.id ? 'text-lime' : 'text-cream/30'} /></button>)}</div>
          <div className={`relative min-h-[360px] overflow-hidden border border-white/[.1] p-7 md:p-10 ${active.accent === 'lime' ? 'bg-[#263020]' : active.accent === 'peach' ? 'bg-[#29221d]' : 'bg-[#18242a]'}`}><div className="absolute right-[-40px] top-[-70px] h-64 w-64 rounded-full border-[45px] border-white/[.04]" /><div className="relative flex h-full flex-col justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-cream/50">{active.tag}</p><h3 className="display mt-6 max-w-[550px] text-3xl leading-[1.05] tracking-[-.055em] md:text-5xl">{active.title}</h3><p className="mt-5 max-w-[430px] text-sm leading-6 text-cream/60">{active.description}</p></div><div className="mt-10 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><div className="display text-6xl tracking-[-.07em] text-lime">{active.result}</div><p className="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-cream/45">{active.resultLabel}</p></div><ul className="max-w-[300px] space-y-2 text-xs leading-5 text-cream/60">{active.details.map(d => <li key={d} className="flex gap-2"><span className="text-lime">—</span>{d}</li>)}</ul></div></div></div></div>
      </div></section>

      <section id="approach" className="mx-auto max-w-[1240px] px-5 py-20 md:px-8 md:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-4 text-[11px] font-bold uppercase tracking-[.2em] text-lime">How I work</p><h2 className="display max-w-[430px] text-4xl tracking-[-.055em] md:text-6xl">Less reporting.<br /><span className="text-cream/40">More revealing.</span></h2></div><div className="border-t rule">{['Start with the human question', 'Find the signal in the noise', 'Make the next move obvious'].map((title, i) => <div key={title} className="flex gap-7 border-b rule py-7 md:gap-14"><span className="text-xs text-lime">0{i+1}</span><div><h3 className="text-lg tracking-[-.02em]">{title}</h3><p className="mt-2 max-w-[430px] text-sm leading-6 text-cream/50">{['Good analysis starts before the dashboard. I align on the decision we are trying to make and the person it will affect.', 'I blend behavioral data, research, and a healthy amount of skepticism to separate movement from meaning.', 'The best insight is one that changes what the team does on Monday. Clear recommendation, clear owner, clear measure.'][i]}</p></div></div>)}</div></div></section>

      <section className="border-y rule bg-[#151812] px-5 py-20 md:px-8"><div className="mx-auto max-w-[1240px]"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="mb-4 text-[11px] font-bold uppercase tracking-[.2em] text-lime">A few answers</p><h2 className="display text-4xl tracking-[-.055em] md:text-5xl">Before we<br />get started.</h2></div><div>{[{q:'What kind of problems do you take on?',a:'I am most useful when a team has plenty of data but not enough clarity: activation, retention, monetization, and the messy questions between them.'},{q:'Do you work with early-stage teams?',a:'Yes. The earlier the better, especially when a thoughtful measurement system can become a competitive advantage rather than a reporting chore.'},{q:'What does a good engagement look like?',a:'A focused question, a shared definition of success, and a clear decision at the end. Usually four to six weeks, with useful work landing every week.'}].map((item, i) => <div key={item.q} className="border-b rule first:border-t"><button className="flex w-full items-center justify-between gap-5 py-6 text-left" onClick={() => setOpenFaq(openFaq === i ? -1 : i)}><span className="text-base md:text-lg">{item.q}</span><ChevronDown size={18} className={`shrink-0 text-lime transition-transform ${openFaq === i ? 'rotate-180' : ''}`} /></button><div className={`grid transition-all duration-300 ${openFaq === i ? 'grid-rows-[1fr] pb-6' : 'grid-rows-[0fr]'}`}><p className="overflow-hidden text-sm leading-6 text-cream/50">{item.a}</p></div></div>)}</div></div></div></section>

      <section id="contact" className="relative overflow-hidden px-5 py-24 md:px-8 md:py-32"><div className="hero-orb absolute left-1/2 top-1/2 h-[600px] w-[600px] -translate-x-1/2 -translate-y-1/2 opacity-60" /><div className="relative mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="mb-5 text-[11px] font-bold uppercase tracking-[.2em] text-lime">Have a good question?</p><h2 className="display max-w-[650px] text-6xl leading-[.92] tracking-[-.075em] md:text-8xl">Let's find<br /><span className="text-lime">the signal.</span></h2><div className="mt-10 flex flex-wrap gap-5 text-sm text-cream/55"><a href="mailto:hello@rahul.work" className="flex items-center gap-2 hover:text-lime"><Mail size={15} /> hello@rahul.work</a><a href="https://linkedin.com" className="flex items-center gap-2 hover:text-lime"><Linkedin size={15} /> LinkedIn</a></div></div><div className="glass rounded-2xl p-6 md:p-8">{sent ? <div className="flex min-h-[270px] flex-col items-center justify-center text-center"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-full bg-lime text-ink"><Check /></div><h3 className="display text-2xl">Message received.</h3><p className="mt-3 text-sm leading-6 text-cream/50">Thanks for reaching out — I'll get back to you within two working days.</p></div> : <form onSubmit={submit}><label className="mb-6 block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.16em] text-cream/45">Your name</span><input required className="w-full border-b border-white/20 bg-transparent py-3 text-sm outline-none transition placeholder:text-cream/25 focus:border-lime" placeholder="How should I call you?" /></label><label className="mb-6 block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.16em] text-cream/45">Email</span><input required type="email" className="w-full border-b border-white/20 bg-transparent py-3 text-sm outline-none transition placeholder:text-cream/25 focus:border-lime" placeholder="you@company.com" /></label><label className="mb-7 block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.16em] text-cream/45">The question</span><textarea required rows="2" className="w-full resize-none border-b border-white/20 bg-transparent py-3 text-sm outline-none transition placeholder:text-cream/25 focus:border-lime" placeholder="What are you trying to figure out?" /></label><button className="flex w-full items-center justify-center gap-3 rounded-full bg-lime py-3.5 text-xs font-bold uppercase tracking-[.14em] text-ink transition hover:bg-cream">Send the note <MoveUpRight size={15} /></button></form>}</div></div></section>
    </main>
    <footer className="border-t rule"><div className="mx-auto flex max-w-[1240px] flex-col gap-4 px-5 py-7 text-[10px] uppercase tracking-[.15em] text-cream/35 sm:flex-row sm:items-center sm:justify-between md:px-8"><span>© 2025 Rahul · Built around better questions</span><a href="#top" className="flex items-center gap-2 transition hover:text-lime">Back to top <ArrowUpRight size={12} /></a></div></footer>
  </div>;
}

export default App;
